name: Call Reusable CD Workflow for Backend

on:
  push:
    branches:
      - master
      - release
      - dev
      
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: false
        default: "master"

jobs:
  call-cd:
    uses: organization/devops/.github/workflows/backend-cd.yml@main
    with:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      branch: ${{ github.event.inputs.branch || github.ref_name }}
      microservices: "payments-service-example,products-service-example,shipping-service-example,orders-service-example"
