name: Call Reusable CD Workflow for Backend

on:
  repository_dispatch:
    types:
      - trigger-cd

  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: false
        default: "master"

jobs:
  call-cd:
    if: ${{ github.event_name != 'repository_dispatch' || github.event.client_payload.branch }}
    uses: obligatorio-devops-agustin/devops/.github/workflows/backend-cd.yml@master
    with:
      branch: ${{ github.event.inputs.branch || github.event.client_payload.branch || github.ref_name }}
      microservices: ${{ github.event.inputs.microservices || github.event.client_payload.microservices }}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
