name: Call Backend CI Workflow

on:
  push:
    branches:
      - develop

  pull_request:
    types: [opened, synchronize, reopened]

  workflow_dispatch: # Habilitar ejecución manual
    inputs:
      branch:
        description: "Branch to analyze"
        required: false
        default: "develop"

jobs:
  sonarcloud:
    name: SonarQube Cloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarQube Cloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
