name: Call Reusable CD Workflow for Backend

on:
  push:
    branches:
      - master
      - release
      - dev
      
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: false
        default: "master"

jobs:
  call-cd:
    uses: obligatorio-devops-agustin/devops/.github/workflows/backend-cd.yml@master
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    with:
      branch: ${{ github.event.inputs.branch || github.ref_name }}
      microservices: "payments-service-example,products-service-example,shipping-service-example,orders-service-example"
